name: Release Obsidian Theme

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "theme.css,manifest.json"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            Theme release ${{ github.ref_name }}
